use crate::modules::field::rental_priceses::RentalList;
use crate::modules::{bank::Bank, color::Color, player::Player};

use crate::modules::{
    constants,
    field::{
        chance::Chance, community_chest::CommunityChest, free_parking::FreeParking,
        general_field::General, go_to_jail::GoToJail, jail_visiting::JailVisiting,
        rail_road::RailRoad, start::Start, street::Street, tax::Tax, utility::Utility, Field,
    },
};
pub fn create_fields() -> Vec<Field> {
    vec![
        Field::Start(Start::new()),
        Field::Street(Street::new(
            String::from("Badstraße"),
            Color::Brown,
            60,
            50,
            RentalList::new(2, 10, 30, 90, 160, 250),
        )),
        Field::CommunityChest(CommunityChest::new()),
        Field::Street(Street::new(
            String::from("Turmstraße"),
            Color::Brown,
            60,
            50,
            RentalList::new(4, 20, 60, 180, 320, 450),
        )),
        Field::Tax(Tax::new(String::from("Einkommenssteuer"), 200)),
        Field::RailRoad(RailRoad::new(String::from("Südbahnhof"))),
        Field::Street(Street::new(
            "Chausseestraße".to_string(),
            Color::LightBlue,
            100,
            50,
            RentalList::new(6, 30, 90, 270, 400, 550),
        )),
        Field::Chance(Chance::new()),
        Field::Street(Street::new(
            "Elisenstraße".to_string(),
            Color::LightBlue,
            100,
            50,
            RentalList::new(6, 30, 90, 270, 400, 550),
        )),
        Field::Street(Street::new(
            "Poststraße".to_string(),
            Color::LightBlue,
            120,
            50,
            RentalList::new(8, 40, 100, 300, 450, 600),
        )),
        Field::JailVisiting(JailVisiting::new(String::from("Zu besuch/Gefängnis"))),
        Field::Street(Street::new(
            "Seestraße".to_string(),
            Color::Pink,
            140,
            100,
            RentalList::new(10, 50, 150, 450, 625, 750),
        )),
        Field::Utility(Utility::new("Elektrizitätswerk".to_string())),
        Field::Street(Street::new(
            "Hafenstraße".to_string(),
            Color::Pink,
            140,
            100,
            RentalList::new(10, 50, 150, 450, 625, 750),
        )),
        Field::Street(Street::new(
            "Neue Straße".to_string(),
            Color::Pink,
            160,
            100,
            RentalList::new(12, 60, 180, 500, 700, 900),
        )),
        Field::RailRoad(RailRoad::new("Westbanhof".to_string())),
        Field::Street(Street::new(
            "Münchner Straße".to_string(),
            Color::Orange,
            180,
            100,
            RentalList::new(14, 70, 200, 550, 750, 950),
        )),
        Field::CommunityChest(CommunityChest::new()),
        Field::Street(Street::new(
            "Wiener Straße".to_string(),
            Color::Orange,
            180,
            100,
            RentalList::new(14, 70, 200, 550, 750, 950),
        )),
        Field::Street(Street::new(
            "Berliner Straße".to_string(),
            Color::Orange,
            200,
            100,
            RentalList::new(16, 80, 220, 600, 800, 1000),
        )),
        Field::FreeParking(FreeParking::new()),
        Field::Street(Street::new(
            "Theaterstraße".to_string(),
            Color::Red,
            220,
            150,
            RentalList::new(18, 90, 250, 700, 875, 1050),
        )),
        Field::Chance(Chance::new()),
        Field::Street(Street::new(
            "Museumstraße".to_string(),
            Color::Red,
            220,
            150,
            RentalList::new(18, 90, 250, 700, 875, 1050),
        )),
        Field::Street(Street::new(
            "Opernplatz".to_string(),
            Color::Red,
            240,
            150,
            RentalList::new(20, 100, 300, 750, 925, 1100),
        )),
        Field::RailRoad(RailRoad::new("Nordbahnhof".to_string())),
        Field::Street(Street::new(
            "Lessingstraße".to_string(),
            Color::Yellow,
            260,
            150,
            RentalList::new(22, 110, 330, 800, 975, 1150),
        )),
        Field::Street(Street::new(
            "Schillerstraße".to_string(),
            Color::Yellow,
            260,
            150,
            RentalList::new(22, 110, 330, 800, 975, 1150),
        )),
        Field::Utility(Utility::new("Wasserwerk".to_string())),
        Field::Street(Street::new(
            "Goethestraße".to_string(),
            Color::Yellow,
            280,
            150,
            RentalList::new(24, 120, 360, 850, 1025, 1200),
        )),
        Field::GoToJail(GoToJail::new()),
        Field::Street(Street::new(
            "Rathausplatz".to_string(),
            Color::Green,
            300,
            200,
            RentalList::new(26, 130, 390, 900, 1100, 1275),
        )),
        Field::Street(Street::new(
            "Hauptstraße".to_string(),
            Color::Green,
            300,
            200,
            RentalList::new(26, 130, 390, 900, 1100, 1275),
        )),
        Field::CommunityChest(CommunityChest::new()),
        Field::Street(Street::new(
            "Bahnhofstraße".to_string(),
            Color::Green,
            320,
            200,
            RentalList::new(28, 150, 450, 1000, 1200, 1400),
        )),
        Field::RailRoad(RailRoad::new("Hauptbahnhof".to_string())),
        Field::Chance(Chance::new()),
        Field::Street(Street::new(
            "Parkstraße".to_string(),
            Color::DarkBlue,
            350,
            200,
            RentalList::new(35, 175, 500, 1100, 1300, 1500),
        )),
        Field::Tax(Tax::new("Luxussteuer".to_string(), 100)),
        Field::Street(Street::new(
            "Schlossallee".to_string(),
            Color::DarkBlue,
            400,
            200,
            RentalList::new(50, 200, 600, 1400, 1700, 2000),
        )),
    ]
}
